In [4]:
# Sample numpy code - generate 2 random number sequences, convert them to square matrices, and multiply them 
# together, element by element
# Generate two random normal sequences

import numpy as np
rand_num_one=np.random.normal(0,1,16)
print("16 random numbers from a standard normal distribution:")
print(rand_num_one)
rand_num_two=np.random.normal(0,1,16)
print(rand_num_two)

# Reshape 16-length sequences into square 4x4 arrays

adjust_rand_one=rand_num_one.reshape(-1,4)
print("Random numbers converted into a 4x4 matrix")
print(adjust_rand_one)
adjust_rand_two=rand_num_two.reshape(-1,4)
print(adjust_rand_two)

# Multiply matrices together elementwise, outputting single result

combined_array=np.multiply(adjust_rand_one,adjust_rand_two)
print("Multiplication output from the random number arrays")
print(combined_array)

16 random numbers from a standard normal distribution:
[-1.04354236  0.87228213  0.38256683  0.21380599 -0.25533373 -0.28709098
 -0.07283281 -0.07666783  0.5461326  -1.29423168  0.37631266 -0.26103829
  0.08999386 -0.79755     0.24154707  0.31774534]
[ 0.43350178  0.19287326  0.01178697 -0.5587183   0.21699192 -1.2764854
 -0.44380115 -0.83944656 -0.14684913  0.09323236  1.05302759  0.6348854
 -1.052317   -1.06721369 -1.41571998 -0.44050694]
Random numbers converted into a 4x4 matrix
[[-1.04354236  0.87228213  0.38256683  0.21380599]
 [-0.25533373 -0.28709098 -0.07283281 -0.07666783]
 [ 0.5461326  -1.29423168  0.37631266 -0.26103829]
 [ 0.08999386 -0.79755     0.24154707  0.31774534]]
[[ 0.43350178  0.19287326  0.01178697 -0.5587183 ]
 [ 0.21699192 -1.2764854  -0.44380115 -0.83944656]
 [-0.14684913  0.09323236  1.05302759  0.6348854 ]
 [-1.052317   -1.06721369 -1.41571998 -0.44050694]]
Multiplication output from the random number arrays
[[-0.45237747  0.1682399   0.0045093  -0.11945732]